#!/usr/bin/env python3

import os
import subprocess


def run_git_cmd(path, cmd):
    cp = subprocess.run(
        ['git', '-C', path] + cmd.split(),
        capture_output=True,
        text=True
    )
    return cp.stdout.strip()


def main():
    count = 0
    for root, dirs, files in os.walk('.'):
        if '.git' in dirs:
            origin_url = run_git_cmd(root, 'remote get-url origin')
            if origin_url.startswith('http'):
                origin_url_components = origin_url.split('/')
                domain, username, repo = origin_url_components[-3:]
                new_origin_url = f'git@{domain}:{username}/{repo}'
                print(
                    f'({root}) Renaming origin url {origin_url!r} --> {new_origin_url!r}'
                )
                run_git_cmd(root, f'remote set-url origin {new_origin_url}')
                count += 1
            dirs.clear()
    print(f'==> {count} repository origin urls renamed to use SSH')

    return 0


if __name__ == '__main__':
    exit(main())
