#!/usr/bin/env python3
import requests
import sys


def help():
    print('Usage: gitignore [FILETYPE]')


def main():
    if '-h' in sys.argv or '--help' in sys.argv:
        help()
        sys.exit(1)

    if len(sys.argv) == 1:
        filetype = 'unknown'
    elif len(sys.argv) == 2:
        filetype = sys.argv[1].strip().lower()
    else:
        help()
        sys.exit(1)

    repo_content_url = 'https://api.github.com/repos/github/gitignore/contents'

    if filetype != 'unknown':
        print(f'Searching for {filetype!r} gitignore file...')

    response = requests.get(repo_content_url)
    response.raise_for_status()

    json_response = response.json()
    for f in json_response:
        try:
            filetype_found, _ = f['name'].split('.')
        except ValueError:
            continue

        filetype_found = filetype_found.lower()
        if filetype == 'unknown':
            print('-> ', filetype_found)
        else:
            if filetype_found == filetype:
                print(f'\nFound {filetype!r} gitignore file.')
                print(f'Downloading gitignore file to {f["name"]}...')
                download_response = requests.get(f['download_url'])
                download_response.raise_for_status()
                with open(f['name'], 'w') as out_file:
                    out_file.write(download_response.text)
                print('...done.')
                return


if __name__ == "__main__":
    main()
