#!/usr/bin/env python3

import argparse
import logging
import random
import subprocess
from shutil import which

import requests
from bs4 import BeautifulSoup

logging.basicConfig(format="[%(levelname)s] %(message)s", level=logging.INFO)


def main():
    if not which("mpv"):
        logging.error("Please install mpv then run the script again.")
        return

    rss_url = "https://musicforprogramming.net/rss.xml"
    parser = argparse.ArgumentParser(
        description="Play music from musicforprogramming.net. "
        "Plays all tracks in order. "
        "Press q to move to the next track. CTRL-C exits the program."
    )
    parser.add_argument("-s", "--shuffle", action="store_true", help="shuffle tracks")
    parser.add_argument(
        "-t",
        "--tracks",
        type=int,
        metavar="N",
        nargs="*",
        help="specify track numbers to play",
    )
    parser.add_argument("-l", "--list", action="store_true", help="list all tracks")
    args = parser.parse_args()
    shuffle = args.shuffle
    tracks = args.tracks

    logging.info("Loading RSS")
    rss_response = requests.get(rss_url)
    rss_response.raise_for_status()
    rss_text = rss_response.text

    urls = list()
    soup = BeautifulSoup(rss_text, features="lxml", parser="lxml")
    link_tags = soup.find_all("enclosure")
    for link in link_tags:
        urls.append(link["url"])

    urls = list(reversed(urls))
    if shuffle:
        random.shuffle(urls)

    if args.list:
        for url in urls:
            print(url)
        return

    if not tracks:
        for url in urls:
            logging.info(f"Playing file: {url}")
            subprocess.run(["mpv", url])
    else:
        total_tracks = len(urls)
        for t in set(tracks):
            # check if track number is invalid
            t_idx = t - 1
            if t_idx < 0 or t_idx >= total_tracks:
                logging.warning(
                    f"Invalid track number {t}, valid tracks are 1-{total_tracks}"
                )
                continue
            track_url = urls[t_idx]
            logging.info(f"Playing file: {track_url}")
            subprocess.run(["mpv", track_url])


if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        logging.info("Bye!")
