#!/usr/bin/env python3

import click
import requests
import subprocess
import shutil
from bs4 import BeautifulSoup


@click.command()
@click.argument("search")
@click.option("-P", "--no-pager", is_flag=True, help="Do not use a pager.")
@click.help_option("-h", "--help")
def main(search, no_pager) -> None:
    """Search for a torrent."""
    click.echo(f"Searching for {search!r} ...", err=True)
    torrent_url = "https://thepiratebay0.org/search/{search}/1/99/0"
    search = "%20".join(search.split())
    endpoint = torrent_url.format(search=search)
    response = requests.get(endpoint)
    response.raise_for_status()
    soup = BeautifulSoup(response.text, "lxml")
    results = soup.select("#searchResult tr:not(:first-child)")
    string_results = list()
    for result in results:
        category = result.select(".vertTh > center > a")
        if category:
            category = ", ".join(c.text for c in category)

        name = result.select(".detName")
        if name:
            name = name[0].text.strip()

        magnet_link = result.select("td > a")
        if magnet_link:
            magnet_link = magnet_link[0]["href"]

        seeders_leechers = result.select("td[align='right']")
        if seeders_leechers:
            seeders = seeders_leechers[0].text
            leechers = seeders_leechers[1].text

        if not all([category, name, magnet_link, seeders_leechers]):
            continue

        text = "download torrent"
        target = magnet_link
        hyperlink = (
            f"\u001b[1m\u001b]8;;{target}\u001b\\{text}" f"\u001b]8;;\u001b\\\u001b[0m"
        )
        string_results.append(
            f"Name        : {name}\n"
            f"Category    : {category}\n"
            f"Seeders     : {seeders}\n"
            f"Leechers    : {leechers}\n"
            f"===> {hyperlink}"
        )

    sep = "\n\n" + "=" * shutil.get_terminal_size()[0] + "\n\n"
    if string_results:
        if no_pager:
            click.echo(sep.join(string_results))
        else:
            process = subprocess.Popen(["less", "-r"], stdin=subprocess.PIPE)
            try:
                if process.stdin is not None:
                    process.stdin.write(sep.join(string_results).encode())
                    process.communicate()
            except Exception as exc:
                print(f"[ERROR] exception occurred: {repr(exc)}")

    else:
        click.echo("No results found.")


if __name__ == "__main__":
    main()
