#!/usr/bin/env bash

source shell_include.sh

ensure_installed fd fzf

arch_wiki_docs="/usr/share/doc/arch-wiki"
if [ ! -d $arch_wiki_docs ]; then
  echo "Arch wiki docs not found."
  echo "Install it with sudo pacman -S arch-wiki-docs"
  exit 1
fi

english_docs="$arch_wiki_docs/html/en"
cd $english_docs
doc_html=$(fd . -e html | fzf --header "Select arch wiki page")

if [ "$doc_html" ]; then
  doc_path="$english_docs/$doc_html"
  echo "Opening $doc_path in default application"
  xdg-open "$doc_path" &>/dev/null
else
  echo "No selection made"
fi
