#!/usr/bin/env python3

import subprocess
import sys
from pathlib import Path
from shutil import which

from bs4 import BeautifulSoup


def download_file(url):
    if not which("wget"):
        print("--> [ERROR] cannot download files. Please install wget first.")
        sys.exit(1)
    subprocess.run(["wget", "--continue", "--show-progress", url])


def main():
    # download rss.xml
    rss_url = "https://musicforprogramming.net/rss.xml"
    if not Path("rss.xml").exists():
        download_file(rss_url)

    urls = list()
    with open("rss.xml") as f:
        soup = BeautifulSoup(f, features="lxml", parser="lxml")
        link_tags = soup.find_all("enclosure")
        for link in link_tags:
            urls.append(link["url"])

    urls = reversed(urls)
    for url in urls:
        print(f"==> Downloading file: {url!r}\n")
        download_file(url)


if __name__ == "__main__":
    main()
